DROP DATABASE if EXISTS tableDB;

CREATE DATABASE tableDB;
USE tableDB;

DROP TABLE if EXISTS buyTBL, userTBL;

CREATE TABLE userTBL(
	userID CHAR(8) NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	birthYear INT NOT NULL,
	addr CHAR(2) NOT NULL,
	mobile1 CHAR(3) NULL,
	mobile2 CHAR(8) NULL,
	height SMALLINT NULL,
	mDate DATE NULL
);

CREATE TABLE buyTBL (
	num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	userid CHAR(8) NOT NULL,
	prodName CHAR(6) NOT NULL,
	groupName CHAR(4) NULL,
	price INT NOT NULL,
	amount SMALLINT NOT NULL,
	FOREIGN KEY(userid) REFERENCES userTBL(userid)
);

INSERT INTO usertbl VALUES
('LSG','이승기', 1987, '서울','011','11111111',182,'2008-08-08'),
('KBS','김범수', 1979, '경남','011','22222222',173,'2012-4-4'),
('KKH','김경호', 1971, '전남','019','33333333',177,'2007-7-7');

INSERT INTO buyTBL VALUES
	(NULL, 'KBS', '운동화 ', NULL , 30,2),
	(NULL, 'KBS', '노트북 ', '전자' , 1000,1);

INSERT INTO buyTBL VALUES
	(NULL, 'JYP', '모니터 ', '전자' , 200,1);
	
ALTER TABLE buytbl
	DROP FOREIGN KEY buytbl_ibfk_1;

　

	